version: "3.7"

networks:
  postgres_local:
    name: postgres_local

volumes:
  postgres: {}

services:
  postgres:
    container_name: postgres-daniel-sales
    image: debezium/postgres:11-alpine
    ports:
      - "5432:5432"
    networks:
      - postgres_local
    environment:
      POSTGRES_USER: daniel
      POSTGRES_PASSWORD: daniel
      POSTGRES_DB: sales
    volumes:
      - postgres:/var/lib/postgresql/data